language: julia
os:
- linux
- osx
julia:
- release
- nightly
notifications:
  email: false
env:
  global:
    secure: UiI3QUsPzofz9Pf7XDVSLAn0zq+ZHv56+kuW5KlSUVCD21tNtnQ6vkjMSZUyfwcG3X8lslBJBhs2Z6fSnZdtHfX4FjQ8jZIqBnp+hmee3O1ZSnp8xCplD1uYlYOg561+QyWJi5+TeSp8fwpEc9k96D4H344RGRtCMfVOgU7ys0M=
